# -*- coding: utf-8 -*-
"""student exam scores

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10XMD2MZBi_CbwAXiwyLur0st6PUfsSVa
"""

!pip install pandas numpy matplotlib seaborn ipywidgets

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ipywidgets as widgets
from IPython.display import display, HTML

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (8, 5)
plt.rcParams['font.size'] = 12

from IPython.display import clear_output

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('student_exam_scores.csv')

np.random.seed(42)
n = 200
data = {
    'student_id': [f'S{str(i).zfill(3)}' for i in range(1, n+1)],
    'hours_studied': np.random.uniform(0, 15, n),
    'sleep_hours': np.random.uniform(4, 10, n),
    'attendance_percent': np.random.uniform(50, 100, n),
    'previous_scores': np.random.uniform(30, 90, n),
    'exam_score': np.random.uniform(20, 100, n)
}
df = pd.DataFrame(data)
df['exam_score'] = df['hours_studied'] * 5 + df['previous_scores'] * 0.3 + np.random.normal(0, 10, n)
df['exam_score'] = df['exam_score'].clip(20, 100)

print("5 data teratas:")
display(df.head())
print("\nInfo dataset:")
df.info()
print("\nStatistik deskriptif:")
df.describe()

# Cek missing values
print(df.isnull().sum())

bins = [0, 5, 10, 15]
labels = ['Rendah (<5 jam)', 'Sedang (5-10 jam)', 'Tinggi (>10 jam)']
df['study_category'] = pd.cut(df['hours_studied'], bins=bins, labels=labels, right=False)
bins_attend = [50, 70, 85, 100]
labels_attend = ['Rendah', 'Sedang', 'Tinggi']
df['attendance_category'] = pd.cut(df['attendance_percent'], bins=bins_attend, labels=labels_attend, right=False)
df['passed'] = df['exam_score'].apply(lambda x: 'Lulus' if x >= 50 else 'Tidak Lulus')

total_siswa = len(df)
rata_hours = df['hours_studied'].mean()
rata_exam = df['exam_score'].mean()
rata_attendance = df['attendance_percent'].mean()

print(f"Total Siswa: {total_siswa}")
print(f"Rata-rata Jam Belajar: {rata_hours:.2f}")
print(f"Rata-rata Nilai Ujian: {rata_exam:.2f}")
print(f"Rata-rata Kehadiran: {rata_attendance:.2f}%")

# 1. Bar Chart: Rata-rata Nilai Ujian per Kategori Jam Belajar
def plot_bar():
    fig, ax = plt.subplots()
    df.groupby('study_category', observed=False)['exam_score'].mean().plot(kind='bar', color='skyblue', edgecolor='black', ax=ax)
    ax.set_title('Rata-rata Nilai Ujian Berdasarkan Jam Belajar', fontweight='bold')
    ax.set_xlabel('Kategori Jam Belajar')
    ax.set_ylabel('Rata-rata Nilai Ujian')
    ax.tick_params(axis='x', rotation=45)
    plt.tight_layout()
    return fig

# 2. Scatter Plot: Jam Belajar vs Nilai Ujian
def plot_scatter():
    fig, ax = plt.subplots()
    scatter = ax.scatter(df['hours_studied'], df['exam_score'],
                         c=df['attendance_percent'], cmap='viridis', alpha=0.7, edgecolors='w', linewidth=0.5)
    ax.set_title('Hubungan Jam Belajar dan Nilai Ujian', fontweight='bold')
    ax.set_xlabel('Jam Belajar')
    ax.set_ylabel('Nilai Ujian')
    cbar = plt.colorbar(scatter, ax=ax)
    cbar.set_label('Kehadiran (%)')
    plt.tight_layout()
    return fig

# 3. Histogram: Distribusi Nilai Ujian
def plot_hist():
    fig, ax = plt.subplots()
    ax.hist(df['exam_score'], bins=15, color='lightcoral', edgecolor='black', alpha=0.7)
    ax.axvline(df['exam_score'].mean(), color='red', linestyle='dashed', linewidth=2, label='Rata-rata')
    ax.set_title('Distribusi Nilai Ujian', fontweight='bold')
    ax.set_xlabel('Nilai Ujian')
    ax.set_ylabel('Frekuensi')
    ax.legend()
    plt.tight_layout()
    return fig

# 4. Box Plot: Nilai Ujian berdasarkan Kategori Tidur
def plot_box():
    bins_sleep = [4, 6, 8, 10]
    labels_sleep = ['Kurang (<6 jam)', 'Cukup (6-8 jam)', 'Baik (>8 jam)']
    df['sleep_category'] = pd.cut(df['sleep_hours'], bins=bins_sleep, labels=labels_sleep, right=False)

    fig, ax = plt.subplots()
    sns.boxplot(x='sleep_category', y='exam_score', data=df, palette='Set2', hue='sleep_category', legend=False, ax=ax)
    ax.set_title('Nilai Ujian berdasarkan Kualitas Tidur', fontweight='bold')
    ax.set_xlabel('Kategori Tidur')
    ax.set_ylabel('Nilai Ujian')
    ax.tick_params(axis='x', rotation=45)
    plt.tight_layout()
    return fig

# 5. Pie Chart: Proporsi Kelulusan
def plot_pie():
    fig, ax = plt.subplots()
    passed_counts = df['passed'].value_counts()
    colors = ['#66b3ff', '#ff9999']
    ax.pie(passed_counts, labels=passed_counts.index, autopct='%1.1f%%', startangle=90, colors=colors,
           wedgeprops={'edgecolor': 'white', 'linewidth': 1})
    ax.set_title('Proporsi Kelulusan Siswa', fontweight='bold')
    plt.tight_layout()
    return fig

# 6. Line Chart: Rata-rata Nilai Ujian per Jam Belajar
def plot_line():
    df['hours_bin'] = pd.cut(df['hours_studied'], bins=10, labels=False)
    line_data = df.groupby('hours_bin')['exam_score'].mean().reset_index()
    line_data['hours_mid'] = line_data['hours_bin'] * 1.5

    fig, ax = plt.subplots()
    ax.plot(line_data['hours_mid'], line_data['exam_score'], marker='o', linestyle='-', color='teal', linewidth=2)
    ax.set_title('Rata-rata Nilai Ujian vs Jam Belajar', fontweight='bold')
    ax.set_xlabel('Jam Belajar (kelompok)')
    ax.set_ylabel('Rata-rata Nilai Ujian')
    plt.tight_layout()
    return fig

def create_kpi_card(title, value, color_bg='#f8f9fa', color_text='#333', icon='📊'):
    """
    Membuat widget HTML untuk KPI card
    """
    html = f"""
    <div style="background-color: {color_bg}; border-radius: 10px; padding: 15px; margin: 5px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2); text-align: center;">
        <div style="font-size: 24px;">{icon}</div>
        <div style="font-size: 16px; color: {color_text}; font-weight: bold;">{title}</div>
        <div style="font-size: 28px; color: #007bff; font-weight: bold;">{value}</div>
    </div>
    """
    return widgets.HTML(html)

kpi1 = create_kpi_card('Total Siswa', f'{total_siswa}', color_bg='#e3f2fd', icon='👥')
kpi2 = create_kpi_card('Rata-rata Jam Belajar', f'{rata_hours:.2f} jam', color_bg='#e8f5e8', icon='📚')
kpi3 = create_kpi_card('Rata-rata Nilai Ujian', f'{rata_exam:.2f}', color_bg='#fff3e0', icon='📝')
kpi4 = create_kpi_card('Rata-rata Kehadiran', f'{rata_attendance:.2f}%', color_bg='#fce4ec', icon='📅')

import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display

header_html = """
<div style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%);
border-radius: 10px; padding: 20px; margin-bottom: 20px;
text-align: center; color: white;">
    <h1 style="margin:0; font-size: 36px;">📊 Dashboard Analisis Performa Siswa</h1>
    <p style="margin:5px 0 0; font-size: 18px;">
    Analisis data siswa berdasarkan jam belajar, kehadiran, dan nilai ujian
    </p>
</div>
"""
header = widgets.HTML(header_html)

kpi_row = widgets.HBox(
    [kpi1, kpi2, kpi3, kpi4],
    layout=widgets.Layout(justify_content='space-between')
)

box_layout = widgets.Layout(
    width='100%',
    height='360px',
    padding='10px',
    border='none',
    border_radius='12px',
    box_shadow='0 6px 15px rgba(0,0,0,0.15)',
    background_color='white'
)

out1 = widgets.Output(layout=box_layout)
out2 = widgets.Output(layout=box_layout)
out3 = widgets.Output(layout=box_layout)
out4 = widgets.Output(layout=box_layout)
out5 = widgets.Output(layout=box_layout)
out6 = widgets.Output(layout=box_layout)

with out1:
    fig = plot_bar()
    display(fig)
    plt.close(fig)

with out2:
    fig = plot_scatter()
    display(fig)
    plt.close(fig)

with out3:
    fig = plot_hist()
    display(fig)
    plt.close(fig)

with out4:
    fig = plot_box()
    display(fig)
    plt.close(fig)

with out5:
    fig = plot_pie()
    display(fig)
    plt.close(fig)

with out6:
    fig = plot_line()
    display(fig)
    plt.close(fig)

grid = widgets.GridBox(
    children=[out1, out2, out3, out4, out5, out6],
    layout=widgets.Layout(
        grid_template_columns='repeat(3, 1fr)',
        grid_auto_rows='380px',
        grid_gap='20px',
        margin='20px 0'
    )
)

dashboard = widgets.VBox(
    [header, kpi_row, grid],
    layout=widgets.Layout(
        padding='25px',
        background_color='#f5f7fa'
    )
)

display(dashboard)